image: "gelbpunkt/python:gcc10"

before_script:
  - apk add --no-cache git gcc musl-dev
  - python --version
  - pip install -r requirements-dev.txt

stages:
  - Static Analysis

black:
  stage: Static Analysis
  script:
    - black .
    - ash -c '[ -z "$(git status --porcelain)" ] || exit 1'

isort:
  stage: Static Analysis
  script:
    - isort -rc .
    - ash -c '[ -z "$(git status --porcelain)" ] || exit 1'

flake8:
  stage: Static Analysis
  script:
    - flake8
