image: "gelbpunkt/python:ci"

before_script:
  - python --version
  - echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && apk add podman

stages:
  - Static Analysis
  - Test Podman Build

black:
  stage: Static Analysis
  script:
    - black --version
    - black .
    - ash -c '[ -z "$(git status --porcelain)" ] || exit 1'

isort:
  stage: Static Analysis
  script:
    - isort --version
    - isort .
    - ash -c '[ -z "$(git status --porcelain)" ] || exit 1'

flake8:
  stage: Static Analysis
  script:
    - flake8 --version
    - flake8

build:
  stage: Test Podman Build
  script:
    - podman --version
    - podman build --storage-driver vfs --runtime runc -t idlerpg:latest .
