image: "python:3.8.0-alpine3.10"

before_script:
  - apk add --no-cache git
  - python --version
  - pip install -r requirements-dev.txt

stages:
  - Static Analysis

black:
  stage: Static Analysis
  script:
  - black .

isort:
  stage: Static Analysis
  script:
  - isort -rc .

flake8:
  stage: Static Analysis
  script:
  - flake8
