image: "python:3.8.0-alpine3.10"

before_script:
  - apk add --no-cache git gcc musl-dev
  - pip install https://github.com/Gelbpunkt/alpine-python-3.8-wheels/raw/master/wheels/regex-2019.8.19-cp38-cp38-linux_x86_64.whl
  - python --version
  - pip install -r requirements-dev.txt

stages:
  - Static Analysis

black:
  stage: Static Analysis
  script:
    - black .

isort:
  stage: Static Analysis
  script:
    - isort -rc .

flake8:
  stage: Static Analysis
  script:
    - flake8
