image: "gelbpunkt/python:ci"

before_script:
  - python --version

stages:
  - Static Analysis

black:
  stage: Static Analysis
  script:
    - black --version
    - black .
    - ash -c '[ -z "$(git status --porcelain)" ] || exit 1'

isort:
  stage: Static Analysis
  script:
    - isort --version
    - isort .
    - ash -c '[ -z "$(git status --porcelain)" ] || exit 1'

flake8:
  stage: Static Analysis
  script:
    - flake8 --version
    - flake8
