arch:
  - amd64
  - arm64
dist: bionic
language: minimal

before_install:
  - . /etc/os-release
  - sudo sh -c "echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_19.10/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
  - curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_19.10/Release.key | sudo apt-key add -
  - sudo apt update
  - sudo apt upgrade -y
  - sudo apt -y install podman uidmap
  - sudo touch /etc/sub{u,g}id
  - sudo usermod --add-subuids 10000-75535 $(whoami)
  - sudo usermod --add-subgids 10000-75535 $(whoami)


script:
  - podman build -t gelbpunkt/idlerpg:latest .
