version: '3.7'
services:
  postgres:
    image: postgres/11.5-alpine
    ports:
    - "5432:5432"
    volumes:
    - postgres:/var/lib/postgresql
    restart: always
  redis:
    image: redis/5.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data
  idlerpg:
    build: .

networks:
  redis-net:

volumes:
  postgres:
  redis-data:
